import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load Integral CF Bold
const integralCF = localFont({
  src: [
    { path: "./fonts/integral-cf-bold.woff2", weight: "700", style: "normal" },
  ],
  display: "swap",
});

// Load Satoshi fonts (Regular, Medium, Bold)
const satoshi = localFont({
  src: [
    { path: "./fonts/satoshi-bold.woff2", weight: "700", style: "normal" },
    { path: "./fonts/satoshi-medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/satoshi-regular.woff2", weight: "400", style: "normal" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.className} ${integralCF.className} antialiased font-normal`}
      >
        {children}
      </body>
    </html>
  );
}
